- name: Install software
  hosts: localhost
  tasks:
    - import_tasks: playbooks/dotfiles/main.yml
    - import_tasks: playbooks/software/main.yml
    - import_tasks: playbooks/software/build/main.yml

    - import_tasks: playbooks/configure/audio.yml
    - import_tasks: playbooks/configure/cron.yml
    - import_tasks: playbooks/configure/geoclue.yml
    - import_tasks: playbooks/configure/keyd.yml
    - import_tasks: playbooks/configure/lightdm.yml
    - import_tasks: playbooks/configure/suspend.yml
    - import_tasks: playbooks/configure/touchpad.yml
    - import_tasks: playbooks/configure/ufw.yml
    - import_tasks: playbooks/configure/misc.yml
