# vim:ft=yaml.ansible

- name: Configure lightdm
  hosts: localhost
  become: true
  tasks:
    - name: Check packages
      apt:
        state: present
        name:
          - lightdm
          - lightdm-gtk-greeter

    - name: Copy config files
      copy:
        src: "{{ item }}"
        dest: /etc/lightdm/"{{ item | basename }}"
      loop:
        - ~/.local/bin/services/lightdm/lightdm.conf
        - ~/.local/bin/services/lightdm/lightdm-gtk-greeter.conf
        # - ~/.local/bin/services/lightdm/slick-greeter.conf
        - ~/.local/bin/services/lightdm/wp.jpg
        - ~/.local/bin/services/lightdm/Xsession

    - name: Enable lightdm service
      systemd_service:
        state: started
        enabled: true
        name: lightdm
