# vim:ft=yaml.ansible

- name: Enable other services
  hosts: localhost
  vars:
    username: lookup('env', 'USER')
  tasks:
    - name: Enable other services
      become: true
      systemd_service:
        name: "{{ item }}"
        state: started
        enabled: true
      loop:
        - NetworkManager
        - auto-cpufreq
        - bluetooth
        - "syncthing@{{ username }}"

    ## Shouldn't be started
    - name: Enable betterlocksreen
      become: true
      systemd_service:
        name: "betterlockscreen@{{ username }}"
        enabled: true

    - name: Enable user services
      systemd_service:
        name: "{{ item }}"
        scope: user
        state: started
        enabled: true
      loop:
        - ssh-agent

    - name: Change user shell
      ansible.builtin.user:
        name: "{{ username }}"
        shell: /usr/bin/zsh
        groups: input
        append: yes

    - name: Use dash as POSIX shell
      become: true
      file:
        src: /bin/dash
        dest: /bin/sh
        state: link

    - name: Link external drives dir
      become: true
      file:
        src: "/media/{{ username }}"
        dest: ~/drives # TODO or /docs/drives?
        state: link

    - name: Mask GTK portal service (causes slow startup of gtk apps)
      systemd_service:
        name: xdg-desktop-portal-gtk
        masked: true
        scope: user

    # - name: Update tldr
    #   command: tldr --update
    #
    # - name: Install node lts
    #   shell: "fnm install lts/latest && fnm default lts/latest"
    #
    # - name: Install auto-cpufreq
    #   become: true
    #   command: auto-cpufreq --install
