# vim:ft=yaml.ansible

- name: Configure ufw
  hosts: localhost
  become: true
  tasks:
    - name: Check packages
      apt:
        state: present
        name: ufw

    - name: Deny all trafic
      ufw:
        policy: deny

    - name: Allow stuff
      ufw:
        name: "{{ item }}"
        rule: allow
      loop:
        - qbittorrent
        - syncthing

    - name: Allow local network
      ufw:
        src: 192.168.0.0/24
        rule: allow

    - name: Limit ssh
      ufw:
        rule: limit
        port: ssh
        proto: tcp
        src: 192.168.0.0/24

    - name: Enable ufw
      ufw:
        state: enabled

    - name: Enable ufw service
      systemd_service:
        state: started
        enabled: true
        name: ufw
