# vim:ft=yaml.ansible

- name: Link dotfiles
  include_tasks: link.yml
  loop:
    - src: ~/docs/dotfiles/dotconfig
      dest: ~/.config
    - src: ~/docs/dotfiles/dotlocal/share/applications
      dest: ~/.local/share/applications
    - src: ~/docs/dotfiles/dotlocal/xdg/icons
      dest: ~/.local/share/xdg/icons
    - src: ~/docs/dotfiles/dotlocal/bin
      dest: ~/.local
      itself: true

- name: Create directories
  file:
    path: "{{ item }}"
    state: directory
  loop:
    - ~/.config/systemd/user
